# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ardinugraha/Documents/Workshop/gridfluxv4

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ardinugraha/Documents/Workshop/gridfluxv4

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/ardinugraha/Documents/Workshop/gridfluxv4/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ardinugraha/Documents/Workshop/gridfluxv4/CMakeFiles /home/ardinugraha/Documents/Workshop/gridfluxv4//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ardinugraha/Documents/Workshop/gridfluxv4/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gridflux

# Build rule for target.
gridflux: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gridflux
.PHONY : gridflux

# fast build rule for target.
gridflux/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gridflux.dir/build.make CMakeFiles/gridflux.dir/build
.PHONY : gridflux/fast

src/core/geometry.o: src/core/geometry.c.o
.PHONY : src/core/geometry.o

# target to build an object file
src/core/geometry.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gridflux.dir/build.make CMakeFiles/gridflux.dir/src/core/geometry.c.o
.PHONY : src/core/geometry.c.o

src/core/geometry.i: src/core/geometry.c.i
.PHONY : src/core/geometry.i

# target to preprocess a source file
src/core/geometry.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gridflux.dir/build.make CMakeFiles/gridflux.dir/src/core/geometry.c.i
.PHONY : src/core/geometry.c.i

src/core/geometry.s: src/core/geometry.c.s
.PHONY : src/core/geometry.s

# target to generate assembly for a file
src/core/geometry.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gridflux.dir/build.make CMakeFiles/gridflux.dir/src/core/geometry.c.s
.PHONY : src/core/geometry.c.s

src/core/logger.o: src/core/logger.c.o
.PHONY : src/core/logger.o

# target to build an object file
src/core/logger.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gridflux.dir/build.make CMakeFiles/gridflux.dir/src/core/logger.c.o
.PHONY : src/core/logger.c.o

src/core/logger.i: src/core/logger.c.i
.PHONY : src/core/logger.i

# target to preprocess a source file
src/core/logger.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gridflux.dir/build.make CMakeFiles/gridflux.dir/src/core/logger.c.i
.PHONY : src/core/logger.c.i

src/core/logger.s: src/core/logger.c.s
.PHONY : src/core/logger.s

# target to generate assembly for a file
src/core/logger.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gridflux.dir/build.make CMakeFiles/gridflux.dir/src/core/logger.c.s
.PHONY : src/core/logger.c.s

src/core/window_manager.o: src/core/window_manager.c.o
.PHONY : src/core/window_manager.o

# target to build an object file
src/core/window_manager.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gridflux.dir/build.make CMakeFiles/gridflux.dir/src/core/window_manager.c.o
.PHONY : src/core/window_manager.c.o

src/core/window_manager.i: src/core/window_manager.c.i
.PHONY : src/core/window_manager.i

# target to preprocess a source file
src/core/window_manager.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gridflux.dir/build.make CMakeFiles/gridflux.dir/src/core/window_manager.c.i
.PHONY : src/core/window_manager.c.i

src/core/window_manager.s: src/core/window_manager.c.s
.PHONY : src/core/window_manager.s

# target to generate assembly for a file
src/core/window_manager.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gridflux.dir/build.make CMakeFiles/gridflux.dir/src/core/window_manager.c.s
.PHONY : src/core/window_manager.c.s

src/core/workspace.o: src/core/workspace.c.o
.PHONY : src/core/workspace.o

# target to build an object file
src/core/workspace.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gridflux.dir/build.make CMakeFiles/gridflux.dir/src/core/workspace.c.o
.PHONY : src/core/workspace.c.o

src/core/workspace.i: src/core/workspace.c.i
.PHONY : src/core/workspace.i

# target to preprocess a source file
src/core/workspace.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gridflux.dir/build.make CMakeFiles/gridflux.dir/src/core/workspace.c.i
.PHONY : src/core/workspace.c.i

src/core/workspace.s: src/core/workspace.c.s
.PHONY : src/core/workspace.s

# target to generate assembly for a file
src/core/workspace.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gridflux.dir/build.make CMakeFiles/gridflux.dir/src/core/workspace.c.s
.PHONY : src/core/workspace.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gridflux.dir/build.make CMakeFiles/gridflux.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gridflux.dir/build.make CMakeFiles/gridflux.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gridflux.dir/build.make CMakeFiles/gridflux.dir/src/main.c.s
.PHONY : src/main.c.s

src/platform/x11/x11_atoms.o: src/platform/x11/x11_atoms.c.o
.PHONY : src/platform/x11/x11_atoms.o

# target to build an object file
src/platform/x11/x11_atoms.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gridflux.dir/build.make CMakeFiles/gridflux.dir/src/platform/x11/x11_atoms.c.o
.PHONY : src/platform/x11/x11_atoms.c.o

src/platform/x11/x11_atoms.i: src/platform/x11/x11_atoms.c.i
.PHONY : src/platform/x11/x11_atoms.i

# target to preprocess a source file
src/platform/x11/x11_atoms.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gridflux.dir/build.make CMakeFiles/gridflux.dir/src/platform/x11/x11_atoms.c.i
.PHONY : src/platform/x11/x11_atoms.c.i

src/platform/x11/x11_atoms.s: src/platform/x11/x11_atoms.c.s
.PHONY : src/platform/x11/x11_atoms.s

# target to generate assembly for a file
src/platform/x11/x11_atoms.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gridflux.dir/build.make CMakeFiles/gridflux.dir/src/platform/x11/x11_atoms.c.s
.PHONY : src/platform/x11/x11_atoms.c.s

src/platform/x11/x11_window_manager.o: src/platform/x11/x11_window_manager.c.o
.PHONY : src/platform/x11/x11_window_manager.o

# target to build an object file
src/platform/x11/x11_window_manager.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gridflux.dir/build.make CMakeFiles/gridflux.dir/src/platform/x11/x11_window_manager.c.o
.PHONY : src/platform/x11/x11_window_manager.c.o

src/platform/x11/x11_window_manager.i: src/platform/x11/x11_window_manager.c.i
.PHONY : src/platform/x11/x11_window_manager.i

# target to preprocess a source file
src/platform/x11/x11_window_manager.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gridflux.dir/build.make CMakeFiles/gridflux.dir/src/platform/x11/x11_window_manager.c.i
.PHONY : src/platform/x11/x11_window_manager.c.i

src/platform/x11/x11_window_manager.s: src/platform/x11/x11_window_manager.c.s
.PHONY : src/platform/x11/x11_window_manager.s

# target to generate assembly for a file
src/platform/x11/x11_window_manager.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gridflux.dir/build.make CMakeFiles/gridflux.dir/src/platform/x11/x11_window_manager.c.s
.PHONY : src/platform/x11/x11_window_manager.c.s

src/utils/collections.o: src/utils/collections.c.o
.PHONY : src/utils/collections.o

# target to build an object file
src/utils/collections.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gridflux.dir/build.make CMakeFiles/gridflux.dir/src/utils/collections.c.o
.PHONY : src/utils/collections.c.o

src/utils/collections.i: src/utils/collections.c.i
.PHONY : src/utils/collections.i

# target to preprocess a source file
src/utils/collections.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gridflux.dir/build.make CMakeFiles/gridflux.dir/src/utils/collections.c.i
.PHONY : src/utils/collections.c.i

src/utils/collections.s: src/utils/collections.c.s
.PHONY : src/utils/collections.s

# target to generate assembly for a file
src/utils/collections.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gridflux.dir/build.make CMakeFiles/gridflux.dir/src/utils/collections.c.s
.PHONY : src/utils/collections.c.s

src/utils/memory.o: src/utils/memory.c.o
.PHONY : src/utils/memory.o

# target to build an object file
src/utils/memory.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gridflux.dir/build.make CMakeFiles/gridflux.dir/src/utils/memory.c.o
.PHONY : src/utils/memory.c.o

src/utils/memory.i: src/utils/memory.c.i
.PHONY : src/utils/memory.i

# target to preprocess a source file
src/utils/memory.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gridflux.dir/build.make CMakeFiles/gridflux.dir/src/utils/memory.c.i
.PHONY : src/utils/memory.c.i

src/utils/memory.s: src/utils/memory.c.s
.PHONY : src/utils/memory.s

# target to generate assembly for a file
src/utils/memory.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gridflux.dir/build.make CMakeFiles/gridflux.dir/src/utils/memory.c.s
.PHONY : src/utils/memory.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... gridflux"
	@echo "... src/core/geometry.o"
	@echo "... src/core/geometry.i"
	@echo "... src/core/geometry.s"
	@echo "... src/core/logger.o"
	@echo "... src/core/logger.i"
	@echo "... src/core/logger.s"
	@echo "... src/core/window_manager.o"
	@echo "... src/core/window_manager.i"
	@echo "... src/core/window_manager.s"
	@echo "... src/core/workspace.o"
	@echo "... src/core/workspace.i"
	@echo "... src/core/workspace.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/platform/x11/x11_atoms.o"
	@echo "... src/platform/x11/x11_atoms.i"
	@echo "... src/platform/x11/x11_atoms.s"
	@echo "... src/platform/x11/x11_window_manager.o"
	@echo "... src/platform/x11/x11_window_manager.i"
	@echo "... src/platform/x11/x11_window_manager.s"
	@echo "... src/utils/collections.o"
	@echo "... src/utils/collections.i"
	@echo "... src/utils/collections.s"
	@echo "... src/utils/memory.o"
	@echo "... src/utils/memory.i"
	@echo "... src/utils/memory.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

